# Generated by Django 4.0.1 on 2022-10-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_rename_user_bookableobject_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
