# Generated by Django 4.0.1 on 2022-10-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
