# Generated by Django 4.0.1 on 2022-10-03 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('jobsapp', '0013_job_dummy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='BookableObject',
        ),
    ]
